DROP TABLE f_usuario;
DROP TABLE f_concepto_facturado;
DROP TABLE f_factura;
DROP TABLE f_logo;
DROP TABLE f_direccion_empresa;
DROP TABLE f_empresas;
DROP TABLE f_cliente;
DROP TABLE f_concepto;
DROP TABLE f_usoscfdi;
