INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('G01', 'Adquisicion de mercancias','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('G02', 'Devoluciones, descuentos o bonificaciones','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('G03', 'Gastos en general','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I01', 'Construcciones','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I02', 'Mobilario y equipo de oficina por inversiones','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I03', 'Equipo de transporte','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I04', 'Equipo de computo y accesorios','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I05', 'Dados, troqueles, moldes, matrices y herramental','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I06', 'Comunicaciones telefonicas','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I07', 'Comunicaciones satelitales','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('I08', 'Otra maquinaria y equipo','1');
INSERT INTO f_usoscfdi(clave, descripcion,status) VALUES('P01', 'Por definir','1');
